from django.urls import path
from .views import (
    admin_dashboard,
    calendario_dettaglio,
    calendario_nuovo,
    calendari_lista,
    dipendente_dashboard,
    dipendente_nuovo,
    dipendenti_lista,
    dipendente_elimina,
    calendario_elimina,
    genera_turni_view,
    home,
    login_view,
    logout_view,
    smista_dashboard,
    dipendente_modifica,
    dipendente_turni,
    miei_turni,
    assenza_elimina,
    assenza_modifica,
    assenza_nuova,
    assenze_lista,
    modifica_turno,
    esporta_calendario_excel,
    ripianifica_calendario_view
)

urlpatterns = [
    path("turni/<int:assegnazione_id>/modifica/", modifica_turno, name="modifica_turno"),
    path("assenze/", assenze_lista, name="assenze_lista"),
    path("assenze/nuova/", assenza_nuova, name="assenza_nuova"),
    path("assenze/<int:assenza_id>/modifica/", assenza_modifica, name="assenza_modifica"),
    path("assenze/<int:assenza_id>/elimina/", assenza_elimina, name="assenza_elimina"),
    path("area-dipendente/miei-turni/", miei_turni, name="miei_turni"),
    path("area-dipendente/turni/", dipendente_turni, name="dipendente_turni"),
    path("", home, name="home"),
    path("login/", login_view, name="login_view"),
    path("logout/", logout_view, name="logout_view"),
    path("dashboard/", smista_dashboard, name="smista_dashboard"),
    path("admin-dashboard/", admin_dashboard, name="admin_dashboard"),
    path("dipendente-dashboard/", dipendente_dashboard, name="dipendente_dashboard"),
    path("calendari/<int:calendario_id>/esporta-excel/", esporta_calendario_excel, name="esporta_calendario_excel"),
    path("dipendenti/", dipendenti_lista, name="dipendenti_lista"),
    path("dipendenti/nuovo/", dipendente_nuovo, name="dipendente_nuovo"),
    path("dipendenti/<int:dipendente_id>/elimina/", dipendente_elimina, name="dipendente_elimina"),
    path("dipendenti/<int:dipendente_id>/modifica/",dipendente_modifica,name="dipendente_modifica"),

    path("calendari/", calendari_lista, name="calendari_lista"),
    path("calendari/nuovo/", calendario_nuovo, name="calendario_nuovo"),
    path("calendari/<int:calendario_id>/", calendario_dettaglio, name="calendario_dettaglio"),
    path("calendari/<int:calendario_id>/genera/", genera_turni_view, name="genera_turni"),
    path("calendari/<int:calendario_id>/elimina/", calendario_elimina, name="calendario_elimina"),
    path("calendari/<int:calendario_id>/ripianifica/", ripianifica_calendario_view,name="ripianifica_calendario")
]