# Generated by Django 6.0.3 on 2026-03-06 20:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Dipendente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("cognome", models.CharField(max_length=100)),
                (
                    "livello",
                    models.CharField(
                        choices=[("senior", "Senior"), ("junior", "Junior")],
                        max_length=10,
                    ),
                ),
                ("attivo", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="CalendarioMensile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("anno", models.IntegerField()),
                ("mese", models.IntegerField()),
                ("creato_il", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "unique_together": {("anno", "mese")},
            },
        ),
        migrations.CreateModel(
            name="AssegnazioneTurno",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data", models.DateField()),
                (
                    "turno",
                    models.CharField(
                        choices=[
                            ("M", "Mattina"),
                            ("P", "Pomeriggio"),
                            ("N", "Notte"),
                            ("R", "Riposo"),
                        ],
                        max_length=1,
                    ),
                ),
                (
                    "calendario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="scheduler.calendariomensile",
                    ),
                ),
                (
                    "dipendente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="scheduler.dipendente",
                    ),
                ),
            ],
            options={
                "unique_together": {("dipendente", "data", "calendario")},
            },
        ),
    ]
