# Generated by Django 6.0.3 on 2026-03-07 22:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scheduler", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="assegnazioneturno",
            options={
                "ordering": ["data", "dipendente__cognome"],
                "verbose_name": "Assegnazione turno",
                "verbose_name_plural": "Assegnazioni turni",
            },
        ),
        migrations.AlterModelOptions(
            name="calendariomensile",
            options={
                "ordering": ["-anno", "-mese"],
                "verbose_name": "Calendario mensile",
                "verbose_name_plural": "Calendari mensili",
            },
        ),
        migrations.AlterModelOptions(
            name="dipendente",
            options={
                "ordering": ["cognome", "nome"],
                "verbose_name": "Dipendente",
                "verbose_name_plural": "Dipendenti",
            },
        ),
        migrations.AlterField(
            model_name="assegnazioneturno",
            name="calendario",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="assegnazioni",
                to="scheduler.calendariomensile",
            ),
        ),
        migrations.AlterField(
            model_name="assegnazioneturno",
            name="dipendente",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="assegnazioni",
                to="scheduler.dipendente",
            ),
        ),
    ]
