# Generated by Django 6.0.3 on 2026-03-07 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scheduler", "0002_alter_assegnazioneturno_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="calendariomensile",
            name="stato",
            field=models.CharField(
                choices=[("bozza", "Bozza"), ("generato", "Generato")],
                default="bozza",
                max_length=20,
            ),
        ),
    ]
