# Generated by Django 6.0.3 on 2026-03-07 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scheduler", "0003_calendariomensile_stato"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="dipendente",
            options={"ordering": ["cognome", "nome"]},
        ),
        migrations.AddField(
            model_name="dipendente",
            name="data_nascita",
            field=models.DateField(blank=True, null=True),
        ),
    ]
