# Generated by Django 6.0.3 on 2026-03-08 21:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scheduler", "0005_dipendente_utente"),
    ]

    operations = [
        migrations.CreateModel(
            name="Assenza",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("ferie", "Ferie"),
                            ("malattia", "Malattia"),
                            ("permesso", "Permesso"),
                            ("assenza", "Assenza"),
                        ],
                        max_length=20,
                    ),
                ),
                ("data_inizio", models.DateField()),
                ("data_fine", models.DateField()),
                ("note", models.TextField(blank=True)),
                (
                    "dipendente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assenze",
                        to="scheduler.dipendente",
                    ),
                ),
            ],
            options={
                "verbose_name": "Assenza",
                "verbose_name_plural": "Assenze",
                "ordering": ["-data_inizio", "dipendente__cognome"],
            },
        ),
    ]
