# Generated by Django 6.0.3 on 2026-03-08 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scheduler", "0006_assenza"),
    ]

    operations = [
        migrations.AlterField(
            model_name="assegnazioneturno",
            name="turno",
            field=models.CharField(
                choices=[
                    ("M", "Mattina"),
                    ("P", "Pomeriggio"),
                    ("N", "Notte"),
                    ("R", "Riposo"),
                    ("F", "Ferie"),
                    ("A", "Assenza"),
                    ("L", "Malattia"),
                    ("X", "Permesso"),
                ],
                max_length=1,
            ),
        ),
    ]
