# Generated by Django 6.0.3 on 2026-03-18 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scheduler", "0007_alter_assegnazioneturno_turno"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="dipendente",
            options={
                "ordering": ["cognome", "nome"],
                "verbose_name": "Dipendente",
                "verbose_name_plural": "Dipendenti",
            },
        ),
        migrations.AddField(
            model_name="dipendente",
            name="tipo_contratto",
            field=models.CharField(
                choices=[("full_time", "Full-time"), ("part_time", "Part-time")],
                default="full_time",
                max_length=20,
            ),
        ),
    ]
